### ISSUE TITLE
Issue in reading energyrun file (problem located)

### ISSUE THREAD

**Issue by vishnu2709** [hitliaomq/ELASTIC3rd#1]
Hi,

While using your code, I noticed that in the glue.py file, in the following functions

def write_energyrun(RunStr):
    '''
    Write string to energyrun file
        This function is used to write correct command for calling first principles code
    Parameter
    ---------
        RunStr: str
            The string for run first principles code, e.g. 'mpirun -n 8 vasp_std'
    Return
    ------
        None
    '''
    EPath = os.path.dirname(__file__)
    **FileName = EPath + "\energyrun"**
    fopen = open(FileName, 'w')
    fopen.write(RunStr)
    fopen.close()

def run():
    '''
    Get the run string from energyrun file
    Parameter
    ---------
        None
    Return
    ------
        RunStr: str
            The command calling first principles code.
    '''
    EPath = os.path.dirname(__file__)
    **FileName = EPath + "\energyrun"**
    fopen = open(FileName, 'r')
    for eachline in fopen:
        eachline = eachline.strip("\n")
        RunStr = eachline.strip()
        print(RunStr)
    fopen.close()
    return RunStr

The bold and italicized lines have a bug, the wrong slash is used, which leads to a file read error

**Comment by hitliaomq** [comment]
Hello, @vishnu2709 

Thank you for your using and pointing out this problem. (I developed this code under windows)

I have fixed this issue and made a new commit by replacing the line by the following line.

FileName = os.path.join(EPath, "energyrun")

If you have any other problems, please contact me without hesitasion by open a new issue.

Thank you again.

Best,
Mingqing

**Comment by vishnu2709** [comment]
Thanks
